apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pricehop

resources:
- manifests/namespace.yaml
- manifests/secrets.yaml
- manifests/auth-service.yaml
- manifests/price-service.yaml
- manifests/frontend.yaml
- manifests/api-gateway.yaml

# CI pipeline writes new git-SHA tags here on every push to main.
images:
- name: 975050132599.dkr.ecr.us-east-1.amazonaws.com/pricehop/api-gateway
  newName: 975050132599.dkr.ecr.us-east-1.amazonaws.com/pricehop/api-gateway
  newTag: 4ecac5e
- name: 975050132599.dkr.ecr.us-east-1.amazonaws.com/pricehop/auth-service
  newName: 975050132599.dkr.ecr.us-east-1.amazonaws.com/pricehop/auth-service
  newTag: 4ecac5e
- name: 975050132599.dkr.ecr.us-east-1.amazonaws.com/pricehop/frontend
  newName: 975050132599.dkr.ecr.us-east-1.amazonaws.com/pricehop/frontend
  newTag: 4ecac5e
- name: 975050132599.dkr.ecr.us-east-1.amazonaws.com/pricehop/price-service
  newName: 975050132599.dkr.ecr.us-east-1.amazonaws.com/pricehop/price-service
  newTag: 4ecac5e

labels:
- pairs:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: pricehop
