apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-data-pvc
  namespace: pricehop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: price-data-pvc
  namespace: pricehop
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 2Gi
